flask_Gubanov_project/posts/forms.py
from flask_wtf import FlaskForm
from flask_wtf.file import FileAllowed
from wtforms import StringField, SubmitField, TextAreaField, FileField
from wtforms.validators import DataRequired


class PostForm(FlaskForm):
    title = StringField('Title', validators=[DataRequired()])
    content = TextAreaField('Content', validators=[DataRequired()])
    picture = FileField('Выберете изображение', validators=[FileAllowed(['jpg', 'png'])])
    submit = SubmitField('Опубликовать')


class CommentForm(FlaskForm):
    content = TextAreaField('Content', validators=[DataRequired()])
    submit = SubmitField('Комментировать')

flask_Gubanov_project/main/routes.py
from flask import render_template, Blueprint
from flask_Gubanov_project.models import User, Post


main = Blueprint('main', __name__)


@main.route("/", methods=['GET'])
@main.route("/home", methods=['GET'])
def home():

    last_posts = Post.get_last_post(limit=10)
    top_posts = Post.get_top_posts_by_likes(limit=5)
    top_users = User.get_top_users(limit=5)

    return render_template('home.html',
                           title='Главня',
                           top_posts=top_posts,
                           last_posts=last_posts,
                           top_users=top_users
                           )

flask_Gubanov_project/posts/routes.py
from flask import (render_template, url_for, flash, redirect, request, abort, Blueprint)
from flask_login import current_user, login_required
from wtforms import SubmitField

from flask_Gubanov_project import db
from flask_Gubanov_project.models import Post, Like, Comment
from flask_Gubanov_project.posts.forms import PostForm, CommentForm
from flask_Gubanov_project.users.utils import save_picture

posts = Blueprint('posts', __name__)


@posts.route("/allpost")
@login_required
def allpost():
    page = request.args.get('page', 1, type=int)
    all_posts = Post.query.order_by(Post.date_posted.desc()).paginate(page=page, per_page=5)
    return render_template('allpost.html', posts=all_posts)


@posts.route("/post/new", methods=['GET', 'POST'])
@login_required
def new_post():
    form = PostForm()
    if form.validate_on_submit():
        post = Post(title=form.title.data, content=form.content.data, author=current_user)
        if form.picture.data:
            picture_file = save_picture(form.picture.data, path_save='static/post_images')
            post.post_image = picture_file
        db.session.add(post)
        db.session.commit()
        flash('Ваш пост создан!', 'success')
        return redirect(url_for('posts.allpost'))
    return render_template('create_post.html', title='Новый пост', form=form, legend='Новый пост')


@posts.route("/post/<int:post_id>")
def post(post_id):
    post = Post.query.get_or_404(post_id)
    comments = Comment.get_comments_order_by_desc(post_id)
    try:
        liked = Like.query.filter(Like.post_id == post_id, Like.username == current_user.username).first()
        return render_template('post.html', title=post.title, post=post, liked=liked, comments=comments)
    except AttributeError:
        return render_template('post.html', title=post.title, post=post, comments=comments)


@posts.route("/post/<int:post_id>/update", methods=['GET', 'POST'])
@login_required
def update_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    form = PostForm()
    if form.validate_on_submit():
        post.title = form.title.data
        post.content = form.content.data
        if form.picture.data:
            picture_file = save_picture(form.picture.data, path_save='static/post_images')
            post.post_image = picture_file
        db.session.commit()
        flash('Ваш пост обновлен!', 'success')
        return redirect(url_for('posts.post', post_id=post.id))
    elif request.method == 'GET':
        form.title.data = post.title
        form.content.data = post.content
    return render_template('create_post.html', title='Обновление поста', form=form, legend='Обновление поста')


@posts.route("/post/<int:post_id>/delete", methods=['POST'])
@login_required
def delete_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    db.session.delete(post)
    db.session.commit()
    flash('Ваш пост был удален!', 'success')
    return redirect(url_for('posts.allpost'))


@posts.route("/post/<int:post_id>/like", methods=['POST'])
@login_required
def like_post(post_id):
    try:
        like = Like.query.filter(Like.post_id == post_id, Like.username == current_user.username).first()
        if like:
            flash('Вы уже ставили лайк к этой записи!', 'success')
            return redirect(url_for('posts.post', post_id=post_id))
        else:
            new_like = Like(post_id=post_id, username=current_user.username)
            db.session.add(new_like)
            db.session.commit()
            Post.counter_likes(post_id)
            return redirect(url_for('posts.post', post_id=post_id))
    except Exception as err:
        print(err)
        return redirect(url_for('posts.allpost'))


@posts.route("/post/<int:post_id>/add-comment", methods=['POST'])
@login_required
def add_comment(post_id):
    try:
        data = request.form['comment']
        limit_symbol = 1000
        if isinstance(data, str) and 0 < len(data) < limit_symbol:
            comment = Comment(username=current_user.username, post_id=post_id, content=request.form['comment'])
            db.session.add(comment)
            db.session.commit()
    except Exception as err:
        print(err)
        return redirect(url_for('posts.post', post_id=post_id))
    return redirect(url_for('posts.post', post_id=post_id))


@posts.route("/post/<int:comment_id>/del-comment/<int:post_id>/", methods=['POST'])
@login_required
def delete_comment(post_id, comment_id):
    try:
        c = Comment.query.get(comment_id)
        c.is_deleted = True
        db.session.add(c)
        db.session.commit()
        return redirect(url_for('posts.post', post_id=post_id))
    except Exception as err:
        print(err)
    return redirect(url_for('posts.post', post_id=post_id))

flask_Gubanov_project/users/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from flask_Gubanov_project import db, bcrypt
from flask_Gubanov_project.models import User, Post
from flask_Gubanov_project.users.forms import (RegistrationForm, LoginForm, UpdateAccountForm, RequestResetForm,
                                               ResetPasswordForm)

from flask_Gubanov_project.users.utils import save_picture, send_reset_email


users = Blueprint('users', __name__)


@users.route("/register", methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(username=form.username.data, email=form.email.data, password=hashed_password)
        db.session.add(user)
        db.session.commit()
        flash('Ваша учетная запись была создана! Теперь вы можете войти в систему', 'success')
        return redirect(url_for('users.login'))
    return render_template('register.html', title='Register', form=form)


@users.route("/login", methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('posts.allpost'))

    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('posts.allpost'))
        else:
            flash('Войти не удалось. Пожалуйста, проверьте электронную почту и пароль', 'внимание')
    return render_template('login.html', title='Аутентификация', form=form)


@users.route("/logout")
def logout():
    logout_user()
    return redirect(url_for('main.home'))


@users.route("/account", methods=['GET', 'POST'])
@login_required
def account():
    form = UpdateAccountForm()
    if form.validate_on_submit():
        if form.picture.data:
            picture_file = save_picture(form.picture.data, path_save='static/profile_pics')
            current_user.image_file = picture_file
        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash('Ваш аккаунт был обновлен!', 'success')
        return redirect(url_for('users.account'))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email
        page = request.args.get('page', 1, type=int)
        user = User.query.filter_by(username=form.username.data).first_or_404()
        posts = Post.query.filter_by(author=user).order_by(Post.date_posted.desc()).paginate(page=page, per_page=5)
    image_file = url_for('static', filename='profile_pics/' + current_user.image_file)
    return render_template('account.html', title='Account', image_file=image_file, form=form, posts=posts, user=user)


@users.route("/user/<string:username>")
def user_posts(username):
    page = request.args.get('page', 1, type=int)
    user = User.query.filter_by(username=username).first_or_404()
    posts = Post.query.filter_by(author=user).order_by(Post.date_posted.desc()).paginate(page=page, per_page=5)
    return render_template('user_posts.html', posts=posts, user=user)


@users.route("/reset_password", methods=['GET', 'POST'])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        send_reset_email(user)
        flash('На почту отправлено письмо с инструкциями по сбросу пароля.', 'info')
        return redirect(url_for('users.login'))
    return render_template('reset_request.html', title='Сброс пароля', form=form)


@users.route("/reset_password/<token>", methods=['GET', 'POST'])
def reset_token(token):
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    user = User.verify_reset_token(token)
    if user is None:
        flash('Это недействительный или просроченный токен', 'warning')
        return redirect(url_for('users.reset_request'))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user.password = hashed_password
        db.session.commit()
        flash('Ваш пароль был обновлен! Теперь вы можете авторизоваться', 'success')
        return redirect(url_for('users.login'))
    return render_template('reset_token.html', title='Сброс пароля', form=form)

flask_Gubanov_project/templates/account.html
{% extends "layout.html" %}

{% block style %}
    <style>
        .account-img {width: 100px; height: 100px;}
    </style>
{% endblock style %}

{% block content %}
<div class="reg">
        <div class="reg_body text-center">
            <div class="reg_block">

                <div class="media">
                    <img class="rounded-circle account-img" src="{{ image_file }}">
                    <div class="media-body">
                        <h2 class="account-heading">{{ current_user.username }}</h2>
                        <p class="text-secondary">{{ current_user.email }}</p>
                    </div>
                </div>

                <form method="POST" action="" enctype="multipart/form-data">
                    {{ form.hidden_tag() }}
                    <fieldset class="form-group">
                        
                        {% if form.username.errors %}
                              {{ form.username(class="form-control form-control-lg is-invalid") }}
                                <div class="invalid-feedback">
                                    {% for error in form.username.errors %}
                                        <span>{{ error }}</span>
                                    {% endfor %}
                                </div>
                        {% else %}
                            {{ form.username(class="form-control form-control-sm") }}
                        {% endif %}

                        {{ form.email.label(class="form-control-label") }}
                        {% if form.email.errors %}
                            {{ form.email(class="form-control form-control-lg is-invalid") }}
                                <div class="invalid-feedback">
                                    {% for error in form.email.errors %}
                                        <span>{{ error }}</span>
                                    {% endfor %}
                                </div>
                        {% else %}
                            {{ form.email(class="form-control form-control-lg") }}
                        {% endif %}<br><br>

                        {{ form.picture.label() }}
                        {{ form.picture(class="form-control-file") }}
                        {% if form.picture.errors %}
                            {% for error in form.picture.errors %}
                                <span class="text-danger">{{ error }}</span></br>
                            {% endfor %}
                        {% endif %}

                    </fieldset>

                    <div class="form-group">
                        {{ form.submit(class="btn btn-primary reg-btn") }}
                    </div>

                </form>
            </div>
        </div>
    </div>
{% endblock content %}

flask_Gubanov_project/templates/home.html
{% extends "layout.html" %}

{% block style %}{% endblock style %}

{% block content %}
    <div class="container">
        <main class="row">
            <section class="posts-block block col-8">
                <h3>Последние добавленые записи</h3>
                <div>
                    {% for post in last_posts %}
                        <div class="card w-95">
                            <div class="card-body">
                                <h5 class="card-title"><a href="{{ url_for('posts.post', post_id=post.id) }}">{{ post.title }}</a></h5>
                                <p class="card-text">{{ post.content[:120] }} ...</p>
                                <div class="row justify-content-between">
                                    <div class="col-10">
                                        <small>
                                            <span>Опубликовано: {{ post.date_posted.strftime('%A, %d %B %Y %I:%M %p') }}</span>
                                        </small>
                                    </div>
                                    <div class="col-2 text-center">
                                        <small class="text-muted">
                                            <img src="{{ url_for('static', filename='images/comment_img_mini.png') }}" style="width: 24px;" alt="">
                                            {{ post.comments|length }}
                                        </small>
                                        <small class="text-muted">
                                            <img src="{{ url_for('static', filename='images/like_mini.png') }}" alt="like">
                                            {{ post.total_likes }}
                                        </small>
                                    </div>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                </div> 
            </section>
            <aside class="col-4">
                {% include "inc-sidebar.html" %}
            </aside>
        </main>
    </div>
{% endblock content %}

flask_Gubanov_project/templates/inc-header.html
<header class="header">
        <div class="container">
            <div class="top-block block row justify-content-between text-uppercase">
                <div class="top-block_logo col text-left">
                    {% if current_user.is_authenticated %}
                        <h4>Привет, {{ current_user.username }}!</h4>
                    {% else %}
                        <h4>Здравствуй, гость!</h4>
                    {% endif %}
                </div>
                <div class="top-block_mobile-contact col">blog<span>fox</span></div>
            </div>
            <nav class="navigator">
                <div class="nav_items block bg row text-uppercase">
                    <div class="nav_item col"><a href="{{ url_for('main.home') }}" class="nav_link"><span>главная</span></a></div>
                    <div class="nav_item col"><a href="#" class="nav_link"><span>о проекте</span></a></div>
                    <div class="nav_item col"><a href="#" class="nav_link"><span>контакты</span></a></div>
                        {% if current_user.is_authenticated %}
                            <div class="nav_item col"><a href="{{ url_for('posts.allpost') }}" class="nav_link"><span>все посты</span></a></div>
                            <div class="nav_item col-1">
                                <a href="{{ url_for('posts.allpost') }}" class="nav_link">
                                    <img class="rounded-circle account-img" style="width: 50px; height: 50px; border: 2px solid rgb(210, 210, 210);" src="{{ url_for('static', filename='profile_pics/' + current_user.image_file)}}" alt="">
                                </a>
                            </div>
                        {% else %}
                            <div class="nav_item col"><a href="{{ url_for('users.register') }}" class="nav_link" id="linkReg_"><span>регистрация</span></a></div>
                            <div class="nav_item col"><a href="{{ url_for('users.login') }}" class="nav_link"><span>войти</span></a></div>
                        {% endif %}
                </div>
                    {% if current_user.is_authenticated %}
                        <div class="nav_manage_user_post row justify-content-between text-center">
                            <div class="col-md-6"></div>
                            <div class="manage_item col"><a href="{{ url_for('posts.new_post') }}" class="nav_link"><span>Создать пост</span></a></div>
                            <div class="manage_item col"><a href="{{ url_for('users.user_posts', username=current_user.username) }}" class="nav_link"><span>Мои посты</span></a></div>
                            <div class="manage_item col"><a href="{{ url_for('users.account') }}" class="nav_link"><span>Профиль</span></a></div>
                            <div class="manage_item col"><a href="{{ url_for('users.logout') }}" class="nav_link"><span>Выйти</span></a></div>  
                        </div>
                        <hr>
                    {% endif %}
            </nav>
        </div>
</header>

flask_Gubanov_project/templates/inc-sidebar.html
<div class="sidebar-block">
    <h3 style="font-weight: 600; font-size: large;">Топ-5 авторов</h3>
    <div class="user row text-center justify-content-between">
        {% for user in top_users %}
            <div class="user_ava col-2">
                <a href="{{ url_for('users.user_posts', username=user.username) }}"><img src="{{ url_for('static', filename='profile_pics/' + user.image_file) }}" class="rounded-circle article-img" style="width: 50px; height: 50px;" alt=""></a>
            </div>
    {% endfor %}
    </div>
    <hr style="border: 2px solid; color:rgb(38, 38, 38)">
    <h3 style="font-weight: 600; font-size: large;">Топ-5 статей</h3>
    {% for post in top_posts %}
        <div class="top-post">
            <a href="{{ url_for('posts.post', post_id=post.id) }}"><h5 style="font-weight: 600; font-size: large; color: orangered;">{{ post.title }}</h5></a>
            {{ post.content[:50] }}...<br>
            <div class="row justify-content-between">
                <div class="col-10"></div>
                <div class="col-2">
                    <small class="text-muted">
                        <img src="{{ url_for('static', filename='images/like_mini.png') }}" alt="like"> 
                        {{ post.total_likes}}
                    </small>    
                </div>
            </div>
            <hr>
        </div>
    {% endfor %}
</div>

flask_Gubanov_project/templates/login.html
{% extends "layout.html" %}

{% block content %}
    <div class="reg">
        <div class="reg_body text-center">
            <div class="reg_block">
                <h3>Авторизация</h3><br>
                <form method="POST" action="">
                    {{ form.hidden_tag() }}
                    <fieldset class="form-group">
                        {{ form.email.label(class="form-control-label") }}
                        {% if form.email.errors %}
                            {{ form.email(class="form-control form-control-lg is-invalid") }}
                            <div class="invalid-feedback">
                                {% for error in form.email.errors %}
                                    <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                        {% else %}
                            {{ form.email(class="form-control form-control-sm") }}
                        {% endif %}

                        {{ form.password.label(class="form-control-label") }}
                        {% if form.password.errors %}
                            {{ form.password(class="form-control form-control-lg is-invalid") }}
                            <div class="invalid-feedback">
                                {% for error in form.password.errors %}
                                    <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                        {% else %}
                            {{ form.password(class="form-control form-control-sm") }}
                        {% endif %}

                        <div class="form-check">
                            {{ form.remember(class="form-check-input") }}
                            {{ form.remember.label(class="form-check-label") }}
                        </div>
                    </fieldset>

                    <div class="form-group">
                        {{ form.submit(class="btn btn-primary reg-btn") }}
                    </div>
                        <br><br>

                    <small style="font-size: 15px; font-weight: 500; margin-top: 26px;">
                        Забыли пароль? <br> <a class="btn btn-primary" href="{{ url_for('users.reset_request') }}">Восстановить</a>
                    </small>
                        <br><br>

                    <small style="font-size: 15px; font-weight: 500; margin-top: 26px;">
                        Нужен аккаунт? <br> <a class="btn btn-primary" href="{{ url_for('users.register') }}">Зарегистрируйтесь</a>
                    </small>

                </form>
            </div>
        </div>
    </div>
{% endblock content %}

flask_Gubanov_project/templates/post.html
{% extends "layout.html" %}

{% block style %}
    <style type="text/css">
        .to-comment {
            width: 100%;
            border: hidden;
            border-bottom: 2px solid blue;
        }
        .to-comment:focus {border: inherit;}
        .comment span {font-style: italic; font-weight: 600;}
        .block-comments {width: 90%;}
        .block-comments ul {list-style: none;}
    </style>
{% endblock style %}

{% block content %}
    <div class="container text-left relative_block" style="width: 1040px;">
        <div class="card mb-3">
            <img src="{{ url_for('static', filename='post_images/' + post.post_image) }}" class="card-img-top" alt="...">
            <div class="card-body">
                <p class="card-text">Автор: <a href="{{ url_for('users.user_posts', username=post.author.username) }}">{{ post.author.username }}</a></p>
                <h3 class="card-title">{{ post.title }}</h3>
                <p class="card-text">{{ post.content }}</p>
                <hr>
                <div class="post_btns row justify-content-end">
                    <div class="col-8">
                        <p class="card-text">
                            <small class="text-muted">
                                Последнее обновление {{ post.date_posted.strftime('%A, %d %B %Y %I:%M %p') }}
                            </small>
                        </p>
                    </div>
                    {% if post.author == current_user %}
                        <div class="post_btn col-2 text-center">
                            <a href="{{ url_for('posts.update_post', post_id=post.id) }}" class="btn btn-primary">Редактировать</a>
                        </div>
                        <div class="post_btn col-2 text-center">
                            <form action="{{ url_for('posts.delete_post', post_id=post.id) }}" method="POST">
                              <input class="btn btn-danger" type="submit" value="Delete">
                            </form>
                        </div>
                    {% else %}
                        {% if liked %}
                            <div class="post_btn col-3 text-center">
                                <small class="text-muted">
                                    Вы уже поставили like
                                </small>
                            </div>
                        {% else %}
                            <div class="post_btn col-2 text-center">
                                <form action="{{ url_for('posts.like_post', post_id=post.id) }}" method="POST">
                                    <input class="btn btn-primary" type="submit" value="Нравится">
                                </form>
                            </div>
                        {% endif %}
                        <div class="col-1 text-center">
                            <small class="text-muted">
                                <img src="{{ url_for('static', filename='images/like_mini.png') }}" alt="">
                                {{ post.total_likes }}
                            </small>
                        </div>
                    {% endif %}                
                </div><br>
                <form action="{{ url_for('posts.add_comment', post_id=post.id) }}" method="POST">
                    <input name="comment" type="text" class="to-comment" placeholder="Оставьте комментарий" autocomplete="off">
                    <br><br>
                    <input class="btn btn-primary" type="submit" value="Комментировать">
                </form><br>
                <div class="block-comments">
                    {% for c in comments %}
                    <ul>
                        {% if c.is_deleted == False %}
                            <a href="{{ url_for('users.user_posts', username=post.author.username) }}" style="font-weight: 800;">{{ c.username }}: </a>{{ c.content }}
                            <p><small>Дата: {{ c.date_commented.strftime('%A, %d %B %Y %I:%M %p') }}</small></p>
                            {% if c.username == current_user.username %}
                                <form action="{{ url_for('posts.delete_comment', comment_id=c.id, post_id=post.id)}}" method="POST">
                                    <input class="btn btn-primary" type="submit" value="Удалить">
                                </form>
                            {% endif %}
                        {% endif %}  
                    </ul>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

flask_Gubanov_project/templates/user_posts.html
{% extends "layout.html" %}

{% block style %}
  <style>
    .card-title a:hover {
      color: orangered;
    }
    .card-title a:hover {
      color: orangered;
    }
    .image img{
      margin: 6px;
      width: 100%;
      border-radius: 8px;
    }
    .card {
      width: 1040px;
      border-radius: 8px;
      box-shadow: 0 0 16px rgba(0, 0, 0, 0.4);
    }
  </style>
{% endblock style %}

{% block content %}
    <div class="container text-left relative_block" style="width: 1040px;">
        <h3 class="mb-3">Посты опубликованы пользователем {{ user.username }} ({{ posts.total }})</h1>
        {% for post in posts.items %}
            <div class="card mb-3">
                <div class="row g-0">
                    <div class="image col-md-4">
                        <img src="{{ url_for('static', filename='post_images/' + post.post_image) }}" alt="">
                    </div>
                    <div class="col-md-8">
                        <div class="card-body">
                            <h5 class="card-title"><a href="{{ url_for('posts.post', post_id=post.id) }}">{{ post.title }}</a></h5>
                            <p class="card-text">{{ post.content[:320] }}...<br><a href="{{ url_for('posts.post', post_id=post.id) }}">Читать далее</a></p>
                            
                            <p class="card-text">Автор: <br>
                                <a href="{{ url_for('users.user_posts', username=post.author.username) }}">
                                  <img class="rounded-circle article-img" style="width: 50px; height: 50px;" src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}">
                                  {{ post.author.username }}
                                </a>
                            </p>
                            <div class="row justify-content-between">
                                <div class="col-10">
                                  <p class="card-text"><small class="text-muted">Опубликовано {{ post.date_posted.strftime('%A, %d %B %Y %I:%M %p') }}</small></p>
                                </div>
                                <div class="col-2">
                                    <div class="post_likes">
                                      <small class="text-muted">
                                        <img src="{{ url_for('static', filename='images/like_mini.png') }}" alt="like">
                                        {{ post.total_likes }}
                                      </small>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>

    <div class="container text-center">
        {% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
            {% if page_num %}
                {% if posts.page == page_num %}
                    <a class="btn btn-primary mb-4" href="{{ url_for('users.user_posts', username=user.username, page=page_num) }}">{{ page_num }}</a>
                {% else %}
                    <a class="btn btn-outline-success mb-4" href="{{ url_for('users.user_posts', username=user.username, page=page_num) }}">{{ page_num }}</a>
                {% endif %}
                {% else %}
                ...
                {% endif %}
        {% endfor %}
    </div>

{% endblock content %}